# Pull node base image
FROM node:19-slim

# Install node dependencies
WORKDIR /app
COPY ./package.json .
COPY ./svelte.config.js .
COPY ./prisma .
COPY ./tsconfig.json .
COPY ./.env .
RUN npm install
RUN npx prisma generate

# Move to container
COPY . .

#Launch app
CMD ["npm", "run", "dev"]
EXPOSE 5173